from abc import ABC, abstractmethod
from collections.abc import AsyncGenerator

from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Normalized chat message structure for LLM conversations."""

    role: str = Field(..., description="'system', 'user', or 'assistant'")
    content: str = Field(..., description="Message text content")


class BaseLLMProvider(ABC):
    """Abstract Base Class for pluggable Large Language Model providers."""

    @property
    @abstractmethod
    def model_name(self) -> str:
        """Name or identifier of the configured model."""
        pass

    @abstractmethod
    async def generate(
        self,
        messages: list[ChatMessage],
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> str:
        """
        Generate a complete non-streamed response for the conversation.
        """
        pass

    @abstractmethod
    async def stream(
        self,
        messages: list[ChatMessage],
        temperature: float | None = None,
        max_tokens: int | None = None,
    ) -> AsyncGenerator[str, None]:
        """
        Stream response tokens asynchronously as they are generated by the LLM.
        """
        pass
